SELECT * FROM TB_USERS;
SELECT * FROM TB_CATEGORIES;

---

INSERT INTO TB_USERS VALUES (NULL, 'Admin', 'admin@teste.com', 'ADMIN', 'ADMIN', 'ACTIVE', NOW(), NULL);
INSERT INTO TB_USERS VALUES (NULL, 'Lucas', 'lucas@teste.com', '123', 'USER', 'ACTIVE', NOW(), NULL);
UPDATE TB_USERS SET NAME = 'Lucas2' WHERE ID = 10;

INSERT INTO TB_CATEGORIES (NAME) VALUES ('CAT1');
UPDATE TB_CATEGORIES SET NAME = 'CAT1-2' WHERE ID = 1;