CREATE TABLE TB_USERS (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(100) NOT NULL,
    CREATION_DATE TIMESTAMP,
    UPDATE_DATE TIMESTAMP
);

CREATE TABLE TB_CATEGORIES (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100)
);