CREATE TABLE TB_USERS (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(100) NOT NULL,
    STATUS VARCHAR(100) NOT NULL,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
-- DROP TABLE TB_USERS;

CREATE TABLE TB_CATEGORIES (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    STATUS VARCHAR(100) DEFAULT 'ACTIVE',
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
-- DROP TABLE TB_CATEGORIES;

